"""Refresh LunaTranslator launcher's embedded Python digests for a custom build.

The upstream signed launcher contains SHA-256 digests generated by
``createsigexe.py``.  A source-customized distribution must either rebuild the
launcher or refresh those digest slots.  This tool performs the latter and
removes the now-invalid upstream Authenticode directory, so Windows and the
launcher both treat the result as an unsigned custom executable instead of a
tampered signed executable.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import struct
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class PeLayout:
    image_base: int
    pointer_format: str
    security_directory_offset: int
    checksum_offset: int
    sections: tuple[tuple[int, int, int], ...]

    def file_offset_to_rva(self, offset: int) -> int:
        for raw_offset, raw_size, virtual_address in self.sections:
            if raw_offset <= offset < raw_offset + raw_size:
                return virtual_address + offset - raw_offset
        raise ValueError(f"File offset 0x{offset:x} is outside PE sections")


def parse_pe_layout(data: bytes) -> PeLayout:
    if data[:2] != b"MZ":
        raise ValueError("Not a PE executable (missing MZ header)")
    pe_offset = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe_offset : pe_offset + 4] != b"PE\0\0":
        raise ValueError("Not a PE executable (missing PE signature)")

    coff_offset = pe_offset + 4
    section_count = struct.unpack_from("<H", data, coff_offset + 2)[0]
    optional_size = struct.unpack_from("<H", data, coff_offset + 16)[0]
    optional_offset = coff_offset + 20
    magic = struct.unpack_from("<H", data, optional_offset)[0]
    if magic == 0x20B:  # PE32+
        image_base = struct.unpack_from("<Q", data, optional_offset + 24)[0]
        pointer_format = "<Q"
        data_directory_offset = optional_offset + 112
    elif magic == 0x10B:  # PE32
        image_base = struct.unpack_from("<I", data, optional_offset + 28)[0]
        pointer_format = "<I"
        data_directory_offset = optional_offset + 96
    else:
        raise ValueError(f"Unsupported PE optional-header magic 0x{magic:x}")

    section_table = optional_offset + optional_size
    sections = []
    for index in range(section_count):
        section_offset = section_table + index * 40
        virtual_address = struct.unpack_from("<I", data, section_offset + 12)[0]
        raw_size = struct.unpack_from("<I", data, section_offset + 16)[0]
        raw_offset = struct.unpack_from("<I", data, section_offset + 20)[0]
        sections.append((raw_offset, raw_size, virtual_address))

    return PeLayout(
        image_base=image_base,
        pointer_format=pointer_format,
        security_directory_offset=data_directory_offset + 4 * 8,
        checksum_offset=optional_offset + 64,
        sections=tuple(sections),
    )


def find_digest_slot(data: bytes, layout: PeLayout, relative_path: str) -> int | None:
    encoded_path = relative_path.encode("utf-16-le") + b"\0\0"
    string_offsets = []
    start = 0
    while True:
        found = data.find(encoded_path, start)
        if found < 0:
            break
        string_offsets.append(found)
        start = found + 2

    candidate_slots = set()
    for string_offset in string_offsets:
        try:
            pointer_value = layout.image_base + layout.file_offset_to_rva(string_offset)
        except ValueError:
            continue
        pointer = struct.pack(layout.pointer_format, pointer_value)
        start = 0
        while True:
            found = data.find(pointer, start)
            if found < 0:
                break
            if found + len(pointer) + hashlib.sha256().digest_size <= len(data):
                candidate_slots.add(found + len(pointer))
            start = found + 1

    if not candidate_slots:
        return None
    if len(candidate_slots) != 1:
        slots = ", ".join(f"0x{slot:x}" for slot in sorted(candidate_slots))
        raise ValueError(f"Ambiguous digest slots for {relative_path}: {slots}")
    return candidate_slots.pop()


def refresh_launcher(launcher: Path, python_root: Path, dry_run: bool = False) -> dict:
    launcher = launcher.resolve()
    python_root = python_root.resolve()
    original = launcher.read_bytes()
    layout = parse_pe_layout(original)
    patched = bytearray(original)
    refreshed = []
    already_current = []
    not_embedded = []

    for source in sorted(python_root.rglob("*.py")):
        relative_path = "LunaTranslator/" + source.relative_to(python_root).as_posix()
        slot = find_digest_slot(original, layout, relative_path)
        if slot is None:
            not_embedded.append(relative_path)
            continue
        digest = hashlib.sha256(source.read_bytes()).digest()
        old_digest = original[slot : slot + len(digest)]
        if old_digest == digest:
            already_current.append(relative_path)
        else:
            patched[slot : slot + len(digest)] = digest
            refreshed.append(relative_path)

    # The upstream certificate signs the original bytes and cannot validly be
    # retained after digest refresh.  Clearing the PE security-directory entry
    # represents the executable honestly as an unsigned custom build.  Leave
    # the detached certificate blob inert to avoid changing section offsets.
    struct.pack_into("<II", patched, layout.security_directory_offset, 0, 0)
    struct.pack_into("<I", patched, layout.checksum_offset, 0)

    if not dry_run:
        handle, temporary_name = tempfile.mkstemp(
            prefix=launcher.name + ".", suffix=".tmp", dir=launcher.parent
        )
        try:
            with os.fdopen(handle, "wb") as output:
                output.write(patched)
            os.replace(temporary_name, launcher)
        except Exception:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
            raise

    return {
        "launcher": str(launcher),
        "refreshed": refreshed,
        "already_current": already_current,
        "not_embedded": not_embedded,
        "security_directory_cleared": True,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("target_dir", type=Path)
    parser.add_argument(
        "--launcher",
        action="append",
        default=["LunaTranslator.exe", "LunaTranslator_admin.exe"],
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    target_dir = args.target_dir.resolve()
    python_root = target_dir / "LunaTranslator"
    if not python_root.is_dir():
        parser.error(f"Missing Python source directory: {python_root}")

    for launcher_name in dict.fromkeys(args.launcher):
        launcher = (target_dir / launcher_name).resolve()
        if launcher.parent != target_dir or not launcher.is_file():
            parser.error(f"Invalid launcher target: {launcher}")
        result = refresh_launcher(launcher, python_root, args.dry_run)
        print(
            f"{launcher.name}: refreshed={len(result['refreshed'])}, "
            f"current={len(result['already_current'])}, "
            f"not_embedded={len(result['not_embedded'])}"
        )
        for relative_path in result["refreshed"]:
            print(f"  refreshed {relative_path}")
        for relative_path in result["not_embedded"]:
            print(f"  not embedded {relative_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
